apiVersion: v1
kind: Service
metadata:
  name: tenant-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: tenant-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tenant-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
